@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "asteroid_app.initial.GameController#GameController(Pane,Scene)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "asteroid_app.initial.GameController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1948342084 { 
   	label=initial
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1208265004 { 
   	label=GameMenu
	labeljust=l
	fillcolor=white
	style=filled
   
   GameMenu1735842547XXXnewGameMenu0[
	label="+ newGameMenu()"
	style=filled
	fillcolor=white
	tooltip="GameMenu

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1947711476 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main1735842547XXXstart80204510[
	label="+ start()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_494086569 { 
   	label=GameController
	labeljust=l
	fillcolor=white
	style=filled
   
   GameController1735842547XXXGameController460819184[
	label="+ GameController()"
	style=filled
	fillcolor=white
	tooltip="GameController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

'edges    
GameMenu1735842547XXXnewGameMenu0 -> GameController1735842547XXXGameController460819184;
Main1735842547XXXstart80204510 -> GameMenu1735842547XXXnewGameMenu0;
    
}
@enduml